[package]
name = "day8"
version = "0.1.0"
authors = ["dani campa <danicampa90@gmail.com>"]
build = "build.rs" # For lalrpop

[build-dependencies]
lalrpop = "0.20.*"

[dependencies]
libutils = { path="../libutils" }
lalrpop-util = {version="0.20.*", features = ["lexer", "unicode"]}
regex = "1.10.*"